SELECT FH.FLAVOR
FROM FIRST_HALF FH
JOIN (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS JULY_ORDER
    FROM JULY
    GROUP BY FLAVOR
) J ON FH.FLAVOR = J.FLAVOR
ORDER BY (FH.TOTAL_ORDER + J.JULY_ORDER) DESC
LIMIT 3;